default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twutter_development
  username: gumball

test:
  <<: *default
  database: twutter_test
  username: gumball

production:
  <<: *default
  database: twutter_production
  username: gumball
